name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
    - name: Run deploy script
      uses: arunchaudhary09/hydpyconf2019@ci-cd
      with:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        KEY: ${{ secrets.KEY }}
        script: whoami
