- name: ls -a via ssh
  on: [push]
  jobs:

    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - name: Run deploy script
        uses: arunchaudhary09/hydpyconf2019@ci-cd
        with:
          command: |
            cd /tmp
            ls -a
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.KEY}}